### PR TITLE
Use latest shell-env (fixing upstream broken dep)

### PR DESCRIPTION
**Pull request by blahah**
This makes https://github.com/sindresorhus/shell-env/issues/12 available downstream and fixes e.g. https://github.com/sindresorhus/fix-path/issues/14 (although fix-path will need a bump once this is released).

### CODE REVIEW

**Comment by blahah** [comment]
I'll do a pass through updating the tests - converted to draft until then

**Comment by sindresorhus** [comment]
Bump

**Comment by drahnieR** [comment]
any update on this?

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/shell-path/releases/tag/v3.0.0

**Pull request closed without merging**
